name: Publish
on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false
      - run: echo "PACKAGE_NAME=$(echo "${GITHUB_REF#refs/tags/}" | sed 's/\(.*\)-[^-]*$/\1/')" >> $GITHUB_ENV
      - run: npm ci
      - run: npx nx build "$PACKAGE_NAME"
      - run: npm publish --access public
        working-directory: dist/packages/${{ env.PACKAGE_NAME }}
