name: Publish package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npm ci
      - run: echo "PACKAGE_NAME=$(echo "${GITHUB_REF#refs/tags/}" | sed 's/\(.*\)-[^-]*$/\1/')" >> $GITHUB_ENV
      - run: npx nx build "$PACKAGE_NAME"
      - run: npm publish --access public
        working-directory: dist/packages/${{ env.PACKAGE_NAME }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
